In [3]:
import numpy as np

In [3]:
np.random.seed(0)
np.random.random((4,3,2))

array([[[0.5488135 , 0.71518937],
        [0.60276338, 0.54488318],
        [0.4236548 , 0.64589411]],

       [[0.43758721, 0.891773  ],
        [0.96366276, 0.38344152],
        [0.79172504, 0.52889492]],

       [[0.56804456, 0.92559664],
        [0.07103606, 0.0871293 ],
        [0.0202184 , 0.83261985]],

       [[0.77815675, 0.87001215],
        [0.97861834, 0.79915856],
        [0.46147936, 0.78052918]]])

In [5]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
arr.reshape((2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [15]:
arr.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [17]:
arr2 = np.random.random((4,3,2))

In [22]:
arr2[0,0]

array([0.11827443, 0.63992102])

In [25]:
arr3 = np.arange(1,9).reshape(2,2,-1)
arr3[1,1,0]

7

In [8]:
arr4 = np.arange(1,10).reshape(3,3)[1:, 1:]
arr4

array([[5, 6],
       [8, 9]])

In [4]:
arr5 = np.random.rand(10).reshape(2,5)
print(arr5)

[[0.74928289 0.63352396 0.91683487 0.93801047 0.45172738]
 [0.31865405 0.14911077 0.02803556 0.11198097 0.47069395]]
