In [1]:
import numpy as np

In [18]:
np.ndarray([3])

array([0., 0., 0.])

In [19]:
np.ndarray([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ndarray([2,3,2])

array([[[1.33654810e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.12465777e-312, 9.50815359e-043]],

       [[2.56946981e+184, 4.81471532e-038],
        [9.30952074e+165, 1.22286310e+161],
        [1.73793625e-047, 1.17054249e-046]]])

In [22]:
np.ndarray([1,2], "str")

array([['', '']], dtype='<U0')

In [23]:
np.ndarray([2,1], "float")

array([[1.33651386e-311],
       [9.34604357e-307]])

In [26]:
np.array([1,2,3.0]).dtype

dtype('float64')

In [29]:
np.array([3,4,5]).astype(np.float64)

array([3., 4., 5.])

In [38]:
np.arange(10).reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.ones([2,3,4], "int")

In [35]:
np.zeros([2,3], "int")

array([[0, 0, 0],
       [0, 0, 0]])